// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case13_class.py */ {

    // module body
// [5:0] class original=Multiplier
struct Multiplier {
// [6:4] function original=mul
int mul(Multiplier self /* readonly */, int x /* readonly */, int y /* readonly */) {
            // [7:8]
            return x * y /* type=int, borrow=value */;
        }
    };

    // main guard body
    int __east_main_guard() {
        // [11:4]
        Multiplier m /* type=Multiplier, borrow=value */ = Multiplier() /* type=Multiplier, borrow=value */;
        // [12:4]
        print(m.mul(6, 7)) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
