// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case25_for_range.py */ {

    // module body
// [5:0] function original=sum_range_29
int sum_range_29(int n /* readonly */) {
        // [6:4]
        int total /* type=int, borrow=value */ = 0 /* type=int, borrow=value */;
// [7:4]
for (auto i /* type=int, borrow=value */ : range(n) /* type=list[int], borrow=value */) {
            // [8:8]
            total /* type=int, borrow=value */ /* Add */= i /* type=int, borrow=value */;
        }
        // [9:4]
        return total /* type=int, borrow=value */;
    }

    // main guard body
    int __east_main_guard() {
        // [13:4]
        print(sum_range_29(5)) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
