// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case08_nested_call.py */ {

    // module body
// [5:0] function original=inc
int inc(int x /* readonly */) {
        // [6:4]
        return x + 1 /* type=int, borrow=value */;
    }
// [9:0] function original=twice
int twice(int x /* mutable */) {
        // [10:4]
        return inc(inc(x)) /* type=int, borrow=value */;
    }

    // main guard body
    int __east_main_guard() {
        // [14:4]
        print(twice(10)) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
