#!/usr/bin/env python3
"""Build C++ sources generated by `py2cpp.py --multi-file`."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNTIME_ROOT = ROOT / "src" / "runtime" / "cpp"
SRC_ROOT = ROOT / "src"
_INCLUDE_RE = re.compile(r'^\s*#include\s+"([^"]+)"', re.MULTILINE)


def _resolve_include(current_path: Path, include_txt: str, include_dir: Path) -> Path | None:
    if include_txt.startswith("runtime/cpp/"):
        cand = SRC_ROOT / include_txt
        return cand if cand.exists() else None
    search_roots = [
        current_path.parent,
        include_dir,
        SRC_ROOT,
    ]
    for base in search_roots:
        cand = base / include_txt
        if cand.exists():
            return cand
    return None


def _runtime_include_targets(path: Path, include_dir: Path) -> list[Path]:
    out: list[Path] = []
    if not path.exists():
        return out
    for inc in _INCLUDE_RE.findall(path.read_text(encoding="utf-8")):
        resolved = _resolve_include(path, inc, include_dir)
        if resolved is not None and str(resolved).startswith(str(RUNTIME_ROOT)):
            out.append(resolved)
    return out


def _discover_runtime_headers(module_sources: list[str], include_dir: Path) -> list[Path]:
    seen: set[Path] = set()
    queue: list[Path] = []
    seed = RUNTIME_ROOT / "core" / "py_runtime.ext.h"
    if seed.exists():
        queue.append(seed)
    for source_txt in module_sources:
        source_path = Path(source_txt)
        if not source_path.is_absolute():
            source_path = ROOT / source_path
        if not source_path.exists():
            continue
        queue.extend(_runtime_include_targets(source_path, include_dir))
    ordered: list[Path] = []
    while queue:
        header = queue.pop(0)
        if header in seen or not header.exists():
            continue
        seen.add(header)
        ordered.append(header)
        queue.extend(_runtime_include_targets(header, include_dir))
    return ordered


def _runtime_cpp_candidates_from_header(header: Path) -> list[Path]:
    out: list[Path] = []
    name = header.name
    if name.endswith(".gen.h"):
        out.append(header.with_name(name[:-len(".gen.h")] + ".gen.cpp"))
        out.append(header.with_name(name[:-len(".gen.h")] + ".ext.cpp"))
    elif name.endswith(".ext.h"):
        out.append(header.with_name(name[:-len(".ext.h")] + ".ext.cpp"))
    return out


def _runtime_cpp_sources(module_sources: list[str], include_dir: Path) -> list[str]:
    """実際に include された runtime header から必要な C++ 実装だけを返す。"""
    out: list[str] = []
    seen_headers: set[Path] = set()
    seen: set[str] = set()
    queue: list[Path] = _discover_runtime_headers(module_sources, include_dir)
    while queue:
        header = queue.pop(0)
        if header in seen_headers:
            continue
        seen_headers.add(header)
        for cpp_path in _runtime_cpp_candidates_from_header(header):
            if not cpp_path.exists():
                continue
            rel = cpp_path.relative_to(ROOT).as_posix()
            if rel in seen:
                continue
            seen.add(rel)
            out.append(rel)
            queue.extend(_runtime_include_targets(cpp_path, include_dir))
    return out


def _load_manifest(path: Path) -> dict[str, object]:
    import json

    obj = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(obj, dict):
        raise RuntimeError("manifest must be JSON object")
    return obj


def _collect_sources(manifest: dict[str, object]) -> list[str]:
    modules_obj = manifest.get("modules")
    if not isinstance(modules_obj, list):
        raise RuntimeError("manifest.modules must be list")
    out: list[str] = []
    i = 0
    while i < len(modules_obj):
        ent = modules_obj[i]
        if isinstance(ent, dict):
            src = ent.get("source")
            if isinstance(src, str) and src != "":
                out.append(src)
        i += 1
    if len(out) == 0:
        raise RuntimeError("manifest has no module sources")
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", help="Path to multi-file manifest.json")
    ap.add_argument("-o", "--output", default="a.out", help="Output executable path")
    ap.add_argument("--std", default="c++20", help="C++ language standard")
    ap.add_argument("--opt", default="-O2", help="Optimization flag")
    args = ap.parse_args(argv)

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"error: manifest not found: {manifest_path}", file=sys.stderr)
        return 1
    manifest = _load_manifest(manifest_path)
    module_sources = _collect_sources(manifest)

    include_dir_obj = manifest.get("include_dir")
    include_dir = include_dir_obj if isinstance(include_dir_obj, str) else str(manifest_path.parent / "include")
    include_dir_path = Path(include_dir)
    if not include_dir_path.is_absolute():
        include_dir_path = (manifest_path.parent / include_dir_path).resolve()

    cmd = [
        "g++",
        f"-std={args.std}",
        args.opt,
        "-I",
        "src",
        "-I",
        "src/runtime/cpp",
        "-I",
        str(include_dir_path),
        *module_sources,
        *_runtime_cpp_sources(module_sources, include_dir_path),
        "-o",
        args.output,
    ]
    p = subprocess.run(cmd)
    return int(p.returncode)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
