#!/usr/bin/env python3
"""Guard runtime marker/layout policy for `pytra-core` and `pytra-gen`.

Policy:
- `src/runtime/<lang>/pytra-gen/**` files must include both:
  - `source: ...`
  - `generated-by: ...`
- `src/runtime/<lang>/pytra-core/**` files must not include generated-source markers.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RUNTIME_ROOT = ROOT / "src" / "runtime"
ALLOWLIST_PATH = ROOT / "tools" / "runtime_core_gen_markers_allowlist.txt"

TARGET_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".go",
    ".h",
    ".hpp",
    ".java",
    ".js",
    ".kt",
    ".lua",
    ".nim",
    ".php",
    ".rb",
    ".rs",
    ".scala",
    ".swift",
    ".ts",
}

SOURCE_RE = re.compile(r"source:\s*src/pytra/", re.IGNORECASE)
GENERATED_BY_RE = re.compile(r"generated-by:\s*", re.IGNORECASE)
CORE_FORBIDDEN_RE = re.compile(r"source:\s*src/pytra/(std|utils|built_in)/", re.IGNORECASE)


@dataclass(frozen=True)
class Finding:
    rel_path: str
    reason: str
    detail: str

    @property
    def key(self) -> str:
        return f"{self.rel_path}:{self.reason}"


def _iter_runtime_files(subdir: str) -> list[Path]:
    out: list[Path] = []
    if not RUNTIME_ROOT.exists():
        return out
    for p in sorted(RUNTIME_ROOT.rglob("*")):
        if not p.is_file():
            continue
        if p.suffix.lower() not in TARGET_SUFFIXES:
            continue
        rel = str(p.relative_to(ROOT)).replace("\\", "/")
        if f"/{subdir}/" not in ("/" + rel):
            continue
        out.append(p)
    return out


def _is_excluded_gen_file(path: Path) -> bool:
    # allow docs/readme under pytra-gen.
    return path.suffix.lower() in {".md", ".txt", ".json"}


def _collect_findings() -> list[Finding]:
    findings: list[Finding] = []

    for p in _iter_runtime_files("pytra-gen"):
        if _is_excluded_gen_file(p):
            continue
        rel = str(p.relative_to(ROOT)).replace("\\", "/")
        txt = p.read_text(encoding="utf-8", errors="ignore")
        if SOURCE_RE.search(txt) is None:
            findings.append(
                Finding(
                    rel_path=rel,
                    reason="gen_missing_source_marker",
                    detail="missing `source:` marker",
                )
            )
        if GENERATED_BY_RE.search(txt) is None:
            findings.append(
                Finding(
                    rel_path=rel,
                    reason="gen_missing_generated_by_marker",
                    detail="missing `generated-by:` marker",
                )
            )

    for p in _iter_runtime_files("pytra-core"):
        rel = str(p.relative_to(ROOT)).replace("\\", "/")
        txt = p.read_text(encoding="utf-8", errors="ignore")
        if CORE_FORBIDDEN_RE.search(txt) is not None:
            findings.append(
                Finding(
                    rel_path=rel,
                    reason="core_contains_generated_source_marker",
                    detail="contains generated source marker in pytra-core",
                )
            )

    uniq: dict[str, Finding] = {}
    for item in findings:
        uniq.setdefault(item.key, item)
    return sorted(uniq.values(), key=lambda x: x.key)


def _read_allowlist(path: Path) -> set[str]:
    if not path.exists():
        return set()
    out: set[str] = set()
    for row in path.read_text(encoding="utf-8").splitlines():
        line = row.strip()
        if line == "" or line.startswith("#"):
            continue
        out.add(line)
    return out


def _write_allowlist(path: Path, keys: list[str]) -> None:
    rows = [
        "# Auto-generated by tools/check_runtime_core_gen_markers.py --write-allowlist",
        "# key format: <repo-relative-path>:<reason>",
        "",
    ] + keys
    path.write_text("\n".join(rows) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="check pytra-core/pytra-gen marker and layout boundaries"
    )
    ap.add_argument(
        "--write-allowlist",
        action="store_true",
        help="overwrite allowlist with current findings",
    )
    args = ap.parse_args()

    findings = _collect_findings()
    key_map = {item.key: item for item in findings}
    keys = sorted(key_map.keys())

    if args.write_allowlist:
        _write_allowlist(ALLOWLIST_PATH, keys)
        print(
            "[OK] wrote allowlist:",
            ALLOWLIST_PATH.relative_to(ROOT),
            f"({len(keys)} entries)",
        )
        return 0

    allowed = _read_allowlist(ALLOWLIST_PATH)
    if len(allowed) == 0:
        if len(keys) == 0:
            print("[OK] runtime core/gen marker guard passed (no findings; allowlist empty)")
            return 0
        print(f"[FAIL] allowlist missing or empty: {ALLOWLIST_PATH.relative_to(ROOT)}")
        print("run: python3 tools/check_runtime_core_gen_markers.py --write-allowlist")
        return 1

    added = sorted(key for key in keys if key not in allowed)
    stale = sorted(key for key in allowed if key not in key_map)

    if len(added) > 0:
        print("[FAIL] runtime core/gen marker policy violations detected:")
        for key in added:
            item = key_map[key]
            print(f"  - {item.rel_path} [{item.reason}] {item.detail}")
        print("fix runtime layout/markers or refresh allowlist:")
        print("  python3 tools/check_runtime_core_gen_markers.py --write-allowlist")
        return 1

    print("[OK] runtime core/gen marker guard passed")
    print(f"  tracked baseline findings: {len(keys)}")
    if len(stale) > 0:
        print(f"  note: stale allowlist entries: {len(stale)} (cleanup recommended)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
