#!/usr/bin/env python3
"""Guard against direct runtime/stdlib symbol branching in non-C++ emitters.

Policy:
- Non-C++ emitters must not hardcode runtime/stdlib dispatch with
  `if/elif ... == "symbol"` style branching for guarded symbols.
- Existing debt is tracked in an explicit allowlist.
- New direct-branch occurrences fail this check.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BACKENDS_ROOT = ROOT / "src" / "backends"
ALLOWLIST_PATH = ROOT / "tools" / "emitter_runtimecall_guardrails_allowlist.txt"

IGNORED_BACKENDS = {"cpp", "common"}
KEY_TOKENS = (
    "callee_name",
    "fn_name",
    "fn_name_raw",
    "attr_name",
    "call_name",
    "method_name",
    "module_id",
    "module_name",
    "owner_mod",
    "imported_mod",
    "export_name",
)
BANNED_SYMBOLS = (
    "Path",
    "dumps",
    "grayscale_palette",
    "loads",
    "perf_counter",
    "py_assert_all",
    "py_assert_eq",
    "py_assert_stdout",
    "py_assert_true",
    "pytra.std.pathlib",
    "pytra.std.test",
    "pytra.std.time",
    "pytra.utils.assertions",
    "pytra.utils.gif",
    "pytra.utils.png",
    "save_gif",
    "write_rgb_png",
)

BRANCH_RE = re.compile(r"^\s*(if|elif)\b")


@dataclass(frozen=True)
class Finding:
    rel_path: str
    line_no: int
    symbol: str
    snippet: str

    @property
    def key(self) -> str:
        return f"{self.rel_path}:{self.line_no}:{self.symbol}"


def _iter_emitter_files() -> list[Path]:
    files: list[Path] = []
    if not BACKENDS_ROOT.exists():
        return files
    for backend_dir in sorted(BACKENDS_ROOT.iterdir()):
        if not backend_dir.is_dir():
            continue
        if backend_dir.name in IGNORED_BACKENDS:
            continue
        emitter_dir = backend_dir / "emitter"
        if not emitter_dir.exists():
            continue
        for path in sorted(emitter_dir.rglob("*.py")):
            if not path.is_file():
                continue
            files.append(path)
    return files


def _collect_findings() -> list[Finding]:
    findings: list[Finding] = []
    for path in _iter_emitter_files():
        rel_path = str(path.relative_to(ROOT))
        for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if BRANCH_RE.match(raw) is None:
                continue
            if not any(token in raw for token in KEY_TOKENS):
                continue
            for symbol in BANNED_SYMBOLS:
                if f'"{symbol}"' in raw or f"'{symbol}'" in raw:
                    findings.append(
                        Finding(
                            rel_path=rel_path,
                            line_no=line_no,
                            symbol=symbol,
                            snippet=raw.strip(),
                        )
                    )
    findings.sort(key=lambda item: item.key)
    return findings


def _read_allowlist(path: Path) -> set[str]:
    if not path.exists():
        return set()
    out: set[str] = set()
    for row in path.read_text(encoding="utf-8").splitlines():
        line = row.strip()
        if line == "" or line.startswith("#"):
            continue
        out.add(line)
    return out


def _write_allowlist(path: Path, keys: list[str]) -> None:
    header = [
        "# Auto-generated by tools/check_emitter_runtimecall_guardrails.py --write-allowlist",
        "# Non-C++ emitter runtime-call direct-branch baseline",
        "",
    ]
    path.write_text("\n".join(header + keys) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Guard non-C++ emitter runtime-call hardcoded branch growth"
    )
    parser.add_argument(
        "--write-allowlist",
        action="store_true",
        help="overwrite allowlist with current findings",
    )
    args = parser.parse_args()

    findings = _collect_findings()
    keys = sorted(item.key for item in findings)
    finding_map = {item.key: item for item in findings}

    if args.write_allowlist:
        _write_allowlist(ALLOWLIST_PATH, keys)
        print(
            "[OK] wrote allowlist:",
            ALLOWLIST_PATH.relative_to(ROOT),
            f"({len(keys)} entries)",
        )
        return 0

    allowed = _read_allowlist(ALLOWLIST_PATH)
    if len(allowed) == 0:
        print(f"[FAIL] allowlist missing or empty: {ALLOWLIST_PATH.relative_to(ROOT)}")
        print("run: python3 tools/check_emitter_runtimecall_guardrails.py --write-allowlist")
        return 1

    added = sorted(key for key in keys if key not in allowed)
    stale = sorted(key for key in allowed if key not in finding_map)

    if len(added) > 0:
        print("[FAIL] new direct runtime-call branch(es) detected:")
        for key in added:
            finding = finding_map[key]
            print(f"  - {finding.rel_path}:{finding.line_no} [{finding.symbol}] {finding.snippet}")
        print("Resolve via lower/IR runtime_call path, or explicitly refresh allowlist after review:")
        print("  python3 tools/check_emitter_runtimecall_guardrails.py --write-allowlist")
        return 1

    print("[OK] emitter runtime-call guardrails passed")
    print(f"  tracked baseline findings: {len(keys)}")
    if len(stale) > 0:
        print(f"  note: stale allowlist entries: {len(stale)} (cleanup recommended)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
